# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stdproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('project_topic', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=30)),
                ('city', models.CharField(default='Default_Value', max_length=80)),
                ('post_code', models.IntegerField(default='Default_Value')),
                ('ref_id', models.CharField(default='Default_Value', max_length=120, unique=True)),
                ('ip_address', models.CharField(default='Default_Value', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('professional', models.CharField(choices=[('Enr', 'Engineering'), ('Compt Sci', 'Computer Science')], max_length=30)),
                ('country', models.CharField(choices=[('Nig', 'Nigeria'), ('Gh', 'Ghana')], max_length=30)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='projectregister.Stdproject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stdproject',
            unique_together=set([('email', 'ref_id', 'phone', 'city', 'post_code', 'professional', 'project_topic', 'abstract', 'country')]),
        ),
    ]
