# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdproject',
            name='project_topic',
            field=models.CharField(max_length=50),
        ),
    ]
